### ISSUE TITLE
The "enabled" property does not work among a set of similar hotkeys

### ISSUE THREAD

**Issue by suterma** [Simolation/vue-hotkey#2]
I have a situation where I have a set of similar hotkey buttons created from a v-for loop. The hotkey keys are the same for all of those. Only one of the buttons should be enabled for hotkey usage at a time, though. However, all buttons should be visible, and usable by mouse/touch click.

Here's how I render tracks (in Compilation.vue):

        
        <template v-for="track in tracks" :key="track.Id">
            <Track
                :track="track"
                :ref="'track-' + track.Id"
                :displayMode="tracksDisplayMode"
            />
        </template>

Then, each track has it's own Hotkey (in Track.vue):

                <Hotkey
                    :enabled="isActiveTrack"
                    :keys="['insert']"
                    v-slot="{ clickRef }"
                >
                    <button
                       ...
                        @click.prevent="createNewCue()"
                        :ref="clickRef"                      
                    >
                    </button>
                </Hotkey>

It does only ever work for the last track, if it happens to the active track (isActiveTrack=true). If I enable all hotkeys all the time also only the last one works (gets the click).

A workaround is to use v-if on the Hotkeys. This way, only the actually rendered button gets the click. However this prevents mouse clicks usage on non-active Tracks. (Unless I also render "hotkey-inert" Buttons, on those)

**Comment by suterma** [comment]
I would suspect the problem is that the same hotkey "keys combination" has multiple registered handlers and only the last added actually gets invoked. It does not make a difference whether "propagate" is set to true.

A solution maybe could be to actually unregister/register the handler on enabled/disabled of the hotkey.

**Comment by Simolation** [comment]
Sorry for the late response.

I resolved the issue in version 2.0.0.
The enabled prop has been changed to disabled to match known HTML element syntax.

**Comment by suterma** [comment]
Hi @Simolation, no need to apologize since you are not obliged to do anything for free. However, I appreciate your effort! I will include the new version in the next release of my Replayer project.

**Comment by suterma** [comment]
Unfortunately this should be reopened or marked as wont-fix, as it is not fixed for the situation as described. The mentioned problem still occurs when there are multiple instances of the <Hotkey> component on a single DOM, listening for the same key combination, even when only one of the is "enabled" at any time.

Problem is, that only the last registered gets the event.

To make it work as I have expected here, you should, in useHotkey.ts, do the same as on mount/unmound for enable/disable. This would actually resolve the confusing handling. Currently, the event is just not emit.

However, I now think, that I misunderstood your intention with the enabled/disabled, and in this case I would suggest that you document this like "Enabling/Disabling a hotkey combination does not register/unregister it, thus each hotkey press (combination) can only be served to one Hotkey component instance per DOM". Or similar. 

Does this make sense? Sorry to bother you with this again.

**Comment by suterma** [comment]
To illustrate the situation, you might want to look at my "DismissiblePanel" component: https://github.com/suterma/replayer-pwa/blob/main/src/components/DismissiblePanel.vue

It registers the "ESC" key as a hotkey and observes clicks outside of the area to emit the dismissed. The above problem arises as soon as I have more than one of it.

**Comment by Simolation** [comment]
Hi @suterma,
I just tried it in a demo repo and it works as expected. When I disable all except of one HotKey instance, only the one which is still enabled fires.
The update in 2.0.0 loops through all registered hotkeys and calls the action for those that are enabled. Previously, only the last registered was called, so it should work now.

**TestComp.vue**
```vue
<template>
  <Hotkey :keys="['esc']" :disabled="id !== 3" @hotkey="action">
    I am id {{ id }}
  </Hotkey>
</template>
<script lang="ts">
import { defineComponent } from "vue";
import Hotkey from "./components/Hotkey.vue";

export default defineComponent({
  components: {
    Hotkey,
  },
  props: {
    id: {
      type: Number,
      required: true,
    },
  },
  emits: ["action"],
  setup(props, { emit }) {
    return { action: () => emit("action", props.id) };
  },
});
</script>
```
**App.vue**
```vue
//...
<TestComp :id="1" @action="action" />
<TestComp :id="2" @action="action" />
<TestComp :id="3" @action="action" />
<TestComp :id="4" @action="action" />
//...
```
And when I press `esc` the action gets correctly called with the number 3.

**Comment by suterma** [comment]
Thanks! It really works now for me. I am sure this was some transient stuff because of caching or something that was not updated in my chain.

Sorry for bothering you, and thanks again for this great component!
